Update Build

diff --git a/Build b/Build
--- a/Build
+++ b/Build
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 # Build script for FleetOnRails API
 echo -e "\n\n"
 echo -e "####################################"
@@ -12,9 +13,7 @@ bundle install || { echo 'my_command failed' ; exit 1; }
 
 # Create test db
 echo -e "\n\nCreating test database"
-bundle exec rake db:create RAILS_ENV=test || { echo 'my_command failed' ; exit 1; }
-bundle exec rake db:migrate RAILS_ENV=test || { echo 'my_command failed' ; exit 1; }
-bundle exec rake db:seed RAILS_ENV=test || { echo 'my_command failed' ; exit 1; }
+bundle exec rake db:migrate:reset RAILS_ENV=test || { echo 'my_command failed' ; exit 1; }
 
 # Run tests
 echo -e "\n\nRunning RSpec tests"
